// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD57c_uTR08T4Byo_qVUYpkfz6WHZqmgD4',
    appId: '1:278882773004:android:0088083cb80bf10d752629',
    messagingSenderId: '278882773004',
    projectId: 'skillspro-81dd6',
    storageBucket: 'skillspro-81dd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBClTZ3mIlvLc1qDhz_BhDNUINu088MdW0',
    appId: '1:278882773004:ios:6084098975c93b7e752629',
    messagingSenderId: '278882773004',
    projectId: 'skillspro-81dd6',
    storageBucket: 'skillspro-81dd6.appspot.com',
    androidClientId: '278882773004-cheop71e5sic1gfd8tbkgtvub36l09bt.apps.googleusercontent.com',
    iosClientId: '278882773004-ajvslcmujqr8fkv66ebanqg0n72f2qoq.apps.googleusercontent.com',
    iosBundleId: 'me.skillspro.skillspro',
  );
}
